services:
  api-gateway:
    build: ./backend/api-gateway
    container_name: api-gateway
    restart: always
    ports:
      - "3810:3000"
    environment:
      - DATABASE_URL=postgresql://steiners:steiners@postgres:5432/mafia_db
    networks:
      - mafia-network
      - global-database-network
    depends_on:
      - linkedin-service

  linkedin-service:
    build: ./backend/linkedin
    container_name: linkedin-service
    restart: always
    networks:
      - mafia-network
      - global-database-network
    depends_on:
      - frontend

  frontend:
    build: ./frontend
    container_name: mafia-frontend
    restart: always
    ports:
      - "81:3000"
    networks:
      - mafia-network

networks:
  mafia-network:
    driver: bridge

  global-database-network:
    external: true
