name: Deploy The Port Mafia

on:
  push:
    branches:
      - main # Triggers production deployment whenever you push to master

jobs:
  deploy:
    name: Build & Run Containerized Stack
    runs-on: self-hosted # <--- Tells GitHub to execute this on your Linux laptop

    steps:
      - name: Checkout Repository Source
        uses: actions/checkout@v4

      - name: Set Up Bun Environment
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Inject Production Configurations
        run: |
          echo "NODE_ENV=production" > ./backend/api-gateway/.env
          echo "NODE_ENV=production" > ./backend/linkedin/.env
          echo "NODE_ENV=production" > ./frontend/.env

      - name: Standardize and Rebuild Containers
        run: |
          docker compose down --remove-orphans

          docker compose up --build -d

          docker image prune -f
